version: 1.0.{build}
os: Default Azure
configuration: Release
platform: x64
clone_folder: c:\projects\OpenTechBFG

environment:
  encryption_key:
    secure: 9Urg0eGnS5HKgBq7lQQAtuwwobSySAi5rtxr2kadkQpOeCxa5PTLL15AJ/RPDgAJ

install:
  - cinst -y nsis
  - SET PATH=%PATH%;C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\

before_build:
- cd c:\projects\OpenTechBFG\
- git submodule init
- git submodule update
- mkdir build
- cd build
- cmake -G "Visual Studio 12 Win64" -DCMAKE_INSTALL_PREFIX=../bin/win8-64 -DOPENAL=OFF -DBUNDLED_FREETYPE=ON ../

build:
  project: C:\projects\OpenTechBFG\build\PACKAGE.vcxproj
  verbosity: normal

test: off

artifacts:
  - path: 'build\OpenTechBFG-*-win64.exe'
    name: OpenTechBFG

on_success:
- ps: >-
    nuget install secure-file -ExcludeVersion

    secure-file\tools\secure-file -decrypt c:\projects\OpenTechBFG\.appveyor\id_rsa.enc -secret $env:encryption_key

    move C:\projects\OpenTechBFG\base C:\projects\OpenTechBFG\build\bin

    $unixtimestamp = [int][double]::Parse((Get-Date -UFormat %s))

    move C:\projects\OpenTechBFG\build\bin C:\projects\OpenTechBFG\build\OpenTechBFG-$unixtimestamp

    [Reflection.Assembly]::LoadWithPartialName( "System.IO.Compression.FileSystem" )

    [System.IO.Compression.ZipFile]::CreateFromDirectory("C:\projects\OpenTechBFG\build\OpenTechBFG-$unixtimestamp", "C:\projects\OpenTechBFG\build\OpenTechBFG-$unixtimestamp.zip")

    if ("$(scp -q -B -i /c/projects/OpenTechBFG/.appveyor/id_rsa -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no /c/projects/OpenTechBFG/build/OpenTechBFG-$unixtimestamp.zip kordex@frs.sourceforge.net:/home/frs/project/opentechengine/snapshot/Windows/VisualStudio/OpenTechEngine-$unixtimestamp.zip)" -or $True) {$True}

deploy:
  release: OpenTechBFG-v$(appveyor_build_version)
  description: 'OpenTechBFG'
  provider: GitHub
  auth_token:
    secure: /FqKMwmidZF3nDlOl6I2QcKQBiPTSA5ZKSzM4tpMYmmNFI48cDnJRIPw6DwFdwVq
  artifact: OpenTechBFG
  draft: false
  prerelease: true
  force_update: true
  tag: $(appveyor_repo_tag_name)
  on:
    appveyor_repo_tag: true
